repos:
  - repo: local
    hooks:
      - id: format
        name: poetry run invoke ruff --action format --fix
        entry: poetry run invoke ruff --action format --fix
        language: system
        # Optionally, restrict file types (e.g. Python only):
        # files: \.py$
        pass_filenames: false  # So it works on all files by default, not by filenames from pre-commit
