# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
hooks:
  -   id: format
      name: Format python
      entry: poetry run invoke ruff --action format --fix
      language: python
      types: [text]