repos:
  - repo: local
    hooks:
      - id: format
        name: Format files
        entry: poetry run invoke ruff --action format --fix
        language: system
        pass_filenames: false
      - id: lint
        name: Lint files
        entry: poetry run invoke ruff --action lint --fix
        language: system
        pass_filenames: false